services:        
    Pluk77\SymfonySphinxBundle\Logger\SphinxLogger:
        autowire: true
        arguments:
            - "@?logger"
        tags:
            - { name: monolog.logger, channel: sphinx }
            
    sphinx.logger: '@Pluk77\SymfonySphinxBundle\Logger\SphinxLogger'
    
    Pluk77\SymfonySphinxBundle\DataCollector\SphinxDataCollector:
        autowire: true
        arguments:
            - '@Pluk77\SymfonySphinxBundle\Logger\SphinxLogger'
        tags:
            - { name: data_collector, template: '@SymfonySphinx/Collector/sphinx.html.twig', id: sphinx }
            
    sphinx.data_collector: '@Pluk77\SymfonySphinxBundle\DataCollector\SphinxDataCollector'
    
    Pluk77\SymfonySphinxBundle\Sphinx\Manager:
        public: true
        autowire: true
        arguments:
            - '@sphinx.logger'
            - '%sphinx.host%'
            - '%sphinx.port%'

    sphinx.manager: '@Pluk77\SymfonySphinxBundle\Sphinx\Manager'
